# Ayaka palette, Tokyo Night format (Omarchy 3.3 generates Ghostty, Waybar, btop, etc. from this)
accent = "#e65c5c"
cursor = "#ffcc66"
foreground = "#e6e6e6"
background = "#262626"
selection_foreground = "#ffffff"
selection_background = "#404040"

color0 = "#262626"
color1 = "#e65c5c"
color2 = "#66cc66"
color3 = "#ffcc66"
color4 = "#6699ff"
color5 = "#cc66cc"
color6 = "#66cccc"
color7 = "#f2f2f2"
color8 = "#404040"
color9 = "#ff6666"
color10 = "#80e680"
color11 = "#ffdd80"
color12 = "#80b3ff"
color13 = "#e680e6"
color14 = "#80e6e6"
color15 = "#ffffff"
